# Base callbacks configuration

learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: ${train.interval}

timer:
  _target_: src.callbacks.timer.Timer
  step: true
  inter_step: false
  epoch: true
  val: true

params:
  _target_: src.callbacks.params.ParamsLog
  total: true
  trainable: true
  fixed: true
